### PR TITLE
Remove val_gazebo from package.xml.

### PR DESCRIPTION
**Pull request by tkoolen**
Fixes the following error during the rosdep install process:
```
val@link02:~/ihmc_catkin_ws$ rosdep install --from-paths src -i -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
ihmc_valkyrie_ros: Cannot locate rosdep definition for [val_gazebo]
```

### CODE REVIEW

**Comment by tkoolen** [comment]
@nmertins

**Comment by nmertins** [comment]
Looking into this now. Is the val_gazebo package no longer available? Or do you want the option to run ihmc_valkyrie_ros without needing all the srcsim stuff?

**Comment by tkoolen** [comment]
I'm assuming it would have been one of the projects listed here: https://gitlab.com/nasa-jsc-robotics (also has r2_gazebo for example). It's not currently in that list.

**Comment by wxmerkt** [comment]
@tkoolen are you logged in and added to the private repositories? I can see it. Edit: @gizatt,@manuelli, @mit.valkyrie are in the access list.

It's required in the dependency list as some of the launch files launch the simulator contained therein for the srcsim (for which there are debians and instructions over on bitbucket/osrf/srcsim).

**Comment by nmertins** [comment]
It looks like val_gazebo is only available from one of OSRF's apt repositories. Setup instructions are here:
https://bitbucket.org/osrf/srcsim/wiki/system_setup
Specifically the step about installing the SRCSim package repository. We still might want to remove the dependency so that this repo isn't tied to the srcsim packages, but that may cause confusion because we have launch scripts referencing Gazebo. I wouldn't be opposed to removing them as well since it looks like they are functionally the same as the real-robot launch scripts.

**Comment by tkoolen** [comment]
Yeah, perhaps moving the Gazebo-dependent launch scripts to their own package might be a good solution; it seems a little silly to have to install the whole SRCSim stack on the onboard computers. Alternatively/additionally, I think a clear set of instructions for installing the IHMC software stack on the onboard computers should be provided. I scraped together these instructions from various sources: https://docs.google.com/document/d/1YUi9qJ8nmFPg0sZgWqOUFnBXqz4EHWJPe8aY3wy0CKs/edit?usp=sharing.

**Comment by nmertins** [comment]
This has been merged into develop. Looks like GitHub didn't recognize it automatically though. Guessing that's because there was also a change in one of the launch files that I had to revert (your branch was using valkyrie_A instead of valkyrie_sim).

@tkoolen would you mind creating a separate issue for adding the install instructions? And then subsequently remind us to look at it several months later? 😉

**Comment by nmertins** [comment]
Apparently this is an open issue with GitHub.
https://github.com/isaacs/github/issues/2
I'll close the PR then if there are no objections.

**Pull request closed without merging**
